### ISSUE TITLE
Crash on starting rc 0.9.5.0

### ISSUE THREAD

**Issue by Zebrazilla** [Valkirie/ControllerService#102]
Failing to launch HandheldCompanion.exe, version 0.9.5.0 on Surface Go 3.

I first installed over the existing 0.9.2.0 install and the crash occurred. I then uninstalled and made sure there were no remnants, rebooted for good measure and installed 0.9.5.0, still there was an instant crash.

When running as administrator there is a .dmp file created, but not when running regular, non-elevated. Not sure if the .dmp is useful. 

In event viewer I found the following when the crash occurs, not running as administrator:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/6796156/162835455-a492c0e1-e337-4cba-b81b-b0291d9648ad.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/6796156/162835513-a2ebc34b-ce7f-470e-93b8-611cbab24e0c.png">
<img width="597" alt="image" src="https://user-images.githubusercontent.com/6796156/162835596-0838c1a6-8a12-4108-b675-c1a752cfcca5.png">
.NET runtime 6.0.0 is installed. Installed by first installing 0.9.2.0 and _not uninstalled or reinstalled_ in conjunction with installing 0.9.5.0.
<img width="317" alt="image" src="https://user-images.githubusercontent.com/6796156/162835864-df2b8b46-20fd-4cb8-a130-33f743bb8d47.png">

**Comment by Zebrazilla** [comment]
Installed .NET 6.0.2 hosting bundle and crashed in the same manner, only this time the EventData states its running 6.0.2 and not 6.0.0 as before:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/6796156/162838324-c4983c25-2342-4b43-be11-e5d7023ba916.png">
<img width="296" alt="image" src="https://user-images.githubusercontent.com/6796156/162838376-8d4430da-28bf-4f09-9dda-04236c3158d9.png">

**Comment by CasperH2O** [comment]
Can confirm and reproduce this issue. The service starts and runs fine on a generic platform (like my desktop) but the GUI crashes and creates a .dmp file.

![Naamloos](https://user-images.githubusercontent.com/14330834/162886608-17330fcc-0e59-4b39-85e7-318153ec1ac0.png)

I can initially not reproduce this on my desktop if I start from VS normal or in debug mode. Setting VS to release, deleting the bin folder and building the solution gets the build process stuck indefinitely after:

`1>Done building project "ControllerCommon.csproj".`

**Comment by Valkirie** [comment]
Interesting. Let me investigate :)

**Comment by Zebrazilla** [comment]
> Can you folks try the following hotfixed release ? https://github.com/Valkirie/ControllerService/releases/tag/bin-rc-0.9.5.1

Uninstalled everything, also previous .NET from 0.9.2.0 and let the installer download it from scratch. Installed hotfix 0.9.5.1 and unfortunately encountered the same error in event viewer:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/6796156/162957570-7fb88169-8022-490b-83c2-38bb83a08167.png">

**Comment by CasperH2O** [comment]
Same for mw. 0.9.5.1 additionally gets DirectX but creates an identically sizes .dmp file and the GUI does not open.

**Comment by Valkirie** [comment]
Could you try re-installing .NET 6 Desktop Runtime?
[https://dotnet.microsoft.com/en-us/download/dotnet/6.0](https://forum.linqpad.net/home/leaving?allowTrusted=1&target=https%3A%2F%2Fdotnet.microsoft.com%2Fen-us%2Fdownload%2Fdotnet%2F6.0)

**Comment by CasperH2O** [comment]
Installed 6.0.4 from the link, the GUI starts!

However, now the service won't start... I also tried opening it directly, it briefly opens the command window and then closes, I made a screenshot and have a .dmp file attached.

[ControllerService.exe.9404.zip](https://github.com/Valkirie/ControllerService/files/8475271/ControllerService.exe.9404.zip)

From the screenshot it seems there's some hardcoded path with a Windows user with your surname @Valkirie .

**Comment by Valkirie** [comment]
More like a process is already running.
https://github.com/Valkirie/ControllerService/blob/7ca84e83a5cfd5669d69097e9285b6cac5a30809/ControllerService/Program.cs#L36

**Comment by Zebrazilla** [comment]
> Could you try re-installing .NET 6 Desktop Runtime? https://dotnet.microsoft.com/en-us/download/dotnet/6.0

Installed [.NET Desktop Runtime 6.0.3](https://download.visualstudio.microsoft.com/download/pr/7f3a766e-9516-4579-aaf2-2b150caa465c/d57665f880cdcce816b278a944092965/windowsdesktop-runtime-6.0.3-win-x64.exe
) only, same a CasperH2O, and could then also start GUI. The service also started without issue for me, so seems like all I had to do was have a .NET Desktop Runtime >6.0.2

**Comment by CasperH2O** [comment]
Good, thanks for providing feedback @Zebrazilla. The 6.0.3 requirement has been commited for a future release. Closing this ticket.
