### ISSUE TITLE
Overlay placement grids do not highlight the accent color with touch, only with mouse

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/ControllerService#103]
As description, when clicking any of the grid blocks with the mouse, they remain the nice accent color (blue, orange etc). However, pressing them with touch, they only change into a slightly different color grey.

**Comment by CasperH2O** [comment]
Found that when you "touch" somewhere else which happens implicitly when moving the mouse away the square is correctly highlighted.

Could still be improved though...

**Comment by Valkirie** [comment]
@CasperH2O can you test this?

**Comment by CasperH2O** [comment]
Fixed!
