### ISSUE TITLE
Checking for update on settings page crashes application

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/ControllerService#106]
Tested with formal 0.9.5.1 and latest commits. App crashes.

Debug mode result:

![image](https://user-images.githubusercontent.com/14330834/163667310-b73cf386-db10-4dae-a88d-94be754dac8f.png)

**Comment by Valkirie** [comment]
Fixed by https://github.com/Valkirie/ControllerService/pull/110/commits/32655d5ba26c9c7a403c8dd16f0a999838f1928b. Temporary fix though as I plan to rewrite the update manager.
