### ISSUE TITLE
Install service button indicates it's usable when stopping -> starting controller service state change

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/ControllerService#12]
The install service button on the settings page of the Controller Helper has it's text turn black instead of greyed out when stopping <-> starting the controller service. Pressing the button does not seem to do anything, so it's probably a GUI state machine issue. 

https://github.com/Valkirie/ControllerService/blob/main/ControllerHelper/ControllerHelper.cs#L979

**Comment by CasperH2O** [comment]
Investigated a bit, it seems that "IsElevated" ie user is admin is used to control the highlight, after switching from stopping to starting there is apparently a short timeout where the state is neither paused, stopped or running and thus defaulting to this. Unsure how to approach fix.

Any pointers welcome @nefarius .

**Comment by nefarius** [comment]
Hm? Where's the offending code in question?

**Comment by CasperH2O** [comment]
https://github.com/Valkirie/ControllerService/blob/main/ControllerHelper/ControllerHelper.cs#L997

**Comment by CasperH2O** [comment]
@nefarius my apologies, I selected the wrong Benjamin from the drop down.

**Comment by CasperH2O** [comment]
Confirmed fixed.
