### ISSUE TITLE
Interface Start Minimized tick not respected when Windows is shutdown with application window open

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/ControllerService#13]
Tested with 0.8.4.2.

Steps to reproduce
- Tick the checkbox for "Start Minimized" on the Settings tab under Interface.
- Tick the checkbox for "Run At Startup" on the Settings tab under Interface.
- Open Controller Helper GUI in windowed or maximized mode.
- Restart Windows (or shutdown and start)
- Login in to Windows
- Controller Helper starts on boot with window opened.

Most likely this is caused by the wanted feature where Controller Helper opens with previous window setting (stored in appdata). 

Note that when the application is minimized to system tray and Windows is restarted with the same settings, it indeed starts in the system tray.

**Comment by Valkirie** [comment]
Almost certain https://github.com/Valkirie/ControllerService/commit/8a68ca6632fa6924b6c22a178d856a26f0c3d822 fixed it. Can you update and test again ?

**Comment by CasperH2O** [comment]
Can still reproduce the issue with the same steps, running latest version (8a68ca6).

**Comment by Valkirie** [comment]
fixed by #34
