### ISSUE TITLE
Sliders show jumpy behaviour when digit amount of number changes

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/ControllerService#131]
Observed while using application 0.9.6.2. Sliders that go from 0 to 100, moving between say 90 and 100 makes the slider ticks move.

![slider](https://user-images.githubusercontent.com/14330834/166117031-50e88768-8e4f-4b5c-a382-c94143707782.gif)

**Comment by Valkirie** [comment]
Fixed
