### ISSUE TITLE
Rumble is not passed through to virtual controllers (Aya Neo Pro 2021)

### ISSUE THREAD

**Issue by koethekoethe** [Valkirie/ControllerService#15]
Steps to replicate:

- While emulating a controller (PS4 or Xbox 360, happens for both) navigate to Steam | Settings | Controller | General Controller Settings
- Select your "Detected Controller" (in this case the emulated controller) and click "Identify" 
- Notice that no vibration occurs
- Repeat the above steps with emulation disabled, this time selecting and identifying the native Aya Neo controller.
- Notice that vibration occurs

This same issue happens during gameplay as well, regardless of the "Vibration Strength" slider setting or controller emulated. The same games rumble works when using the native controller.

Running windows 10 home 21H1 (Latest updates installed) and Controller Service 0.8.4.2

**Comment by Valkirie** [comment]
Thanks for your report @koethekoethe. I fixed the issue for next release :)
