### ISSUE TITLE
Controller Service Uninstall leaves behind various files and folder

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/ControllerService#16]
Tested with a fresh install of 0842. After installation, go through Windows -> Remove program -> Uninstall Controller Service.

Controller service uninstall is performed (controller helper briefly opens?) and uninstall states complete.

Check C:\Program Files\Controller Service

- The folder itself still exists
- Various ControllerService.exe.nnnn.dmp files remain
- Logs folder
- Contents of logs folder

After uninstall, performing a new install the user is (correctly) prompted that that the ControllerService folder already exists.

**Comment by Valkirie** [comment]
I could maybe add a new line to the installer script.
`[UninstallDelete]
Type: filesandordirs; Name: "{app}"
`
