### ISSUE TITLE
[onexplayer mini amd] "Hardware keyboard" button breaks HCs emulation/ OR stops cloaking real gamepad"

### ISSUE THREAD

**Issue by GanJJJJ** [Valkirie/ControllerService#160]
using Onexplayer "Hardware Keyboard mode" button breaks HC until you manually restart HC process
- HC running
- keyboard mode ON
- (drag cursor a bit)
- keyboard off
- HC still running
- joy.cpl: same wireless controller (emulated by HC) stopped responding 

ANOTHER SCENARIO: 
"now it's even more weird"
"now, when I do "keyboard off" with HC still running - it creates uncloaked second gamepad, and both of them respond (so hidhide doesn't work)"
"and after that, without closing GUI i'm stopping HC process, gamepad only mode, starting HC service again - but HC doesn't hidhide "controller (cloud gamepad)" anymore, as if "since this controller appeared while HC is already running - hidhide doesn't connect to it as if it's a thirdparty non-relevant something""

__ i wonder if it makes sense to make HC automatically stop and start again the process, when "hardware controller" is connected again? )
__ it's not really sensitive for me since I use steam gyro+keyboard now most of the times; but for an average onexplayer user it might be a dealbreaker whether to use HC or not, I assume (since they won't even think that the problem is in HC not following up on the disconnected-connected controller

Link to discord discussion: https://discord.com/channels/717181357109018694/911978458802958336/981210135114416229

**Comment by Valkirie** [comment]
Fixed on next build
