### ISSUE TITLE
Application crashes when changing 3D controller overlay model

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/ControllerService#171]
Observed by B-Core and Hylian, as reported on Discord.

Hylian hardware:
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19044 N/A Build 19044
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Hardware is basically 9th gen intel CPU + NVIDIA 2060

Flydigi Apex 2. Using the on-chip XBOX mode from that controller. I think it's recognized as a generic xinput device in that way

Crashdump from Hylian: https://files.catbox.moe/bbesqd.dmp

Using application debug/main release: 0.9.10.4

Logs from B-Core:
[ControllerService20220613.log](https://github.com/Valkirie/ControllerService/files/8907993/ControllerService20220613.log)
[HandheldCompanion20220613.log](https://github.com/Valkirie/ControllerService/files/8907994/HandheldCompanion20220613.log)

**Comment by CasperH2O** [comment]
As @Valkirie found, this culprit appears to be having the option to select an OEM model on a unsupported device: 

https://github.com/Valkirie/ControllerService/blob/7e17fc0a5e0445a4721568a7eaacda3a34cab817/HandheldCompanion/Views/Windows/Overlay.xaml.cs#L146

**Comment by Valkirie** [comment]
Fixed on next build
