### ISSUE TITLE
Prmblems cloaking physical controller with Controller Companion Software

### ISSUE THREAD

**Issue by mrjojo245** [Valkirie/ControllerService#173]
There's a problem where the ControllerService cannot cloak physical controller while Controller Companion Software is installed and running.

Controller Companion software is a software to helps navigate windows environment using controller, comes in handy when use on handheld device. (https://store.steampowered.com/app/367670/Controller_Companion/)

I'm on OneXPlayer Mini Intel i7-1195g7

**Comment by mrjojo245** [comment]
It's not that Controller Companion does not work. But the games detect 2 controller exist at the same time and providing the same input at the same time, one is xbox360 controller from Controller Companion and another one is PS4 Dualshock from ControllerService.

Controller Companion dows use xbox360 controller emulation software to work, this might be the problem.

![image](https://user-images.githubusercontent.com/23228785/174328876-576d4da5-4989-4f99-b706-22ab8409af0b.png)

**Comment by mrjojo245** [comment]
Yes, the profile is definitely applied, and no, there's no log file in the system. (I search with 'Everything' software from voidtools installed on my unit)

**Comment by mrjojo245** [comment]
Update: the problem does not happens if I start Controller Companion after ControllerService.

**Comment by CasperH2O** [comment]
@mrjojo245 thank you for investigating and sharing the solution/work around.

Starting the applications in the right order is usually needed when "things" happen with controller chaining, similar to with using Steam + HC.

I'm closing this issue, as I consider your comment the solution.
