### ISSUE TITLE
Aya Neo Founder is not supported yet?

### ISSUE THREAD

**Issue by ghost573** [Valkirie/ControllerService#198]
![ayaneofe](https://user-images.githubusercontent.com/108908286/177904385-6096a7c9-06f8-4e9d-a842-f74c43b519be.png)

Everything works perfectly, I just find this a little funny.

**Comment by CasperH2O** [comment]
Haha! Indeed! Will add shortly, thank you for bringing it to attention.

**Comment by ghost573** [comment]
No problem, thanks for the great software.
