### ISSUE TITLE
Epic Games Launcher Error After Install

### ISSUE THREAD

**Issue by harbingeralpha** [Valkirie/ControllerService#2]
![EGL](https://user-images.githubusercontent.com/5109929/142973544-109ca4fe-4701-4f5d-95f9-3be2d35edf42.JPG)

XINPUT 1_3.dll error appeared while trying to launch the Epic Games launcher immediately after installing the service (RC 0.4) and restarting an Aya Neo Pro running Windows 10.

**Comment by dnp87** [comment]
I have similar issues with XBoxStat on every Windows launch. Not sure if Controller Service is the culprit, blamed it on Aya Space.

**Comment by Valkirie** [comment]
This is not the first time I hear about that issue but I was never able to reproduce it on a device where AYASpace is not installed.
Let me put the release candidate 0.5 online.

**Comment by Valkirie** [comment]
Please get the rc0.5: https://github.com/Valkirie/ControllerService/releases/tag/bin-rc-0.5

1. Stop the Controller Service by opening services.msc.
2. Stop the Controller Helper if it is running by opening the task manager.
3. Delete your current installation folder entirely.
4. Follow the install instruction from rc0.5

**Comment by dnp87** [comment]
I uninstalled Aya Space since the, but the error still persist. There's a chance Aya Space uninstallation did not help. On other hand, I experience no issue using built-in controller in Steam, did not try to use DS4 virtual controller thought.
Sorry for the long text, just wanted to give you full context.

**Comment by dnp87** [comment]
Missing XINPUT_1.3.dll for XBoxStat.exe is gone after installing 0.5

**Comment by Valkirie** [comment]
Brilliant. rc0.6 will bring even better wrapper support so users will truly have two options to manage applications that doesn't natively support the virtual controller through the profile manager.

1. Create a profile for the targeted application.
2. Set whitelisting (application can still access the physical controller) to true or wrapper (application is tricked and see the virtual controller as a physical XBox controller) to true.
