### ISSUE TITLE
Unable to set TDP lower then 20w in 11.4.2

### ISSUE THREAD

**Issue by minifluff** [Valkirie/ControllerService#224]
In 11.2.0 I was able to set TDP as low as 5w and as high as 30w on OneXplayer which is the proper range. In 11.4.2 lowest TDP is 20w and highest is 60w.

**Comment by CasperH2O** [comment]
Hey @minifluff thank you for reporting. Have not seen this one before, which OneXplayer variant fo you have?

We are working hard on a new release which brings a large amount of fixes/improvements and some extra settings for TDP.

**Comment by minifluff** [comment]
I have the Mini I7 1195G7.

**Comment by CasperH2O** [comment]
@minifluff can you try the latest release? It features a global slider adjustment.

https://github.com/Valkirie/ControllerService/releases/tag/bin-rc-0.11.5.0

**Comment by minifluff** [comment]
Tested. I was able to set the proper TDP vaule range and it worked when setting the limits. It doesn't seem to be causing a issue but the interface shows 0 w as the lowest vaule when I set it to 5 w. so anything 5 w and lower sets it to 5 w

**Comment by minifluff** [comment]
disregard the 0 w in the interface fixed itself when I reajusted the vaules again

**Comment by CasperH2O** [comment]
Great, considering this one fixed!
