### ISSUE TITLE
Build 0.11.6.0 Launch On Startup Not Working 

### ISSUE THREAD

**Issue by KurtusCFlush** [Valkirie/ControllerService#237]
Aya Neo Air, Windows 11 Insider Release Candidate (latest update) : When the Air boots up HC doesn't automatically launch. Tried toggling the setting, tried reinstalling, rebooting, etc. Reverted back to previous build and it launches appropriately.

**Comment by Valkirie** [comment]
Hey, could you try and go to %localappdata%/HandheldCompanion/ and delete all folders there. Then install 0.11.6.0?

**Comment by KurtusCFlush** [comment]
I manually deleted everything leftover from the previous installation (including a folder in Documents) and now it works as should. I can only assume some leftover file was causing the hangup.

**Comment by KurtusCFlush** [comment]
No I don't.
