### ISSUE TITLE
suggestion: turn service on when launching helper

### ISSUE THREAD

**Issue by 1basti1** [Valkirie/ControllerService#24]
A setting that controller service starts, when I start the controller Helper program (yes, I know automatic and manual, but I want it to immediately start when I start the program) would be nice.
And maybe even stop service, when I close helper program.

**Comment by 1basti1** [comment]
Or:
Option to have default Profile = Whitelist

Than the program can run in the background and can only be "activated" when there is a profile for specific games.

**Comment by Valkirie** [comment]
Let me think about that. This should not be too difficult to implement. My only concern being that I don't drown out the user interface.

**Comment by 1basti1** [comment]
Ok.
Let me tell you..
I like to have my device "clean", so something I don't need should be off/deactivated whatever.

I like controller Helper, but only for certain games. Everything else (especially some(?) UWP games just don't work with it) I will want to use the normal built in controller.

And when service starts with helper (and closes) It would be super fast to enable it and play a game

**Comment by Valkirie** [comment]
#64 fixed it.
