### ISSUE TITLE
PS Now Integration

### ISSUE THREAD

**Issue by cory-eheart** [Valkirie/ControllerService#25]
I apologize if this is the wrong area to ask this. I've been attempting to use this software to play PS4 games on my Aya Neo through PSNow. However, I get a wireless controller disconnected issue when attempting to play any PS4 game. The issue does not exist when navigating PSNow menus or PS3 games. Is there a solution?

**Comment by CasperH2O** [comment]
This has been looked into and discussed on the Discord server, this is indeed a confirmed issue. It seems somewhere in the last week PS4 games have stopped working. As older versions of controller service that used to work fine now also have this problem it seems to be related to PS Now.

Currently no solution available.

**Comment by Valkirie** [comment]
@cory-eheart can you check again? It works again here... Most likely Sony doing crap.

**Comment by cory-eheart** [comment]
I will check when I get back. Currently in a college class.

**Comment by cory-eheart** [comment]
@Valkirie unfortunately no luck. Still getting a controller disconnected error when starting god of war

**Comment by Valkirie** [comment]
Could it be you're using an instable connection?

**Comment by cory-eheart** [comment]
I am going to say that I've been discussing this issue on the discord as DirtyDeedsDoneDirtCheap, and I am using an Aya Neo (so no poor connection). I will be leaving the issue open so you know it is still here, but I will continue my troubleshooting through discord.

**Comment by CasperH2O** [comment]
PS Now should work with HC, altough it seems something broke with the input in version 0.9.9.x, 0.9.8.x should be OK. 

If you're still around @cory-eheart could you check confirm?
