### ISSUE TITLE
notice: Discord link down

### ISSUE THREAD

**Issue by cory-eheart** [Valkirie/ControllerService#26]
I am trying to join the discord but the link has expired/is invalid.

**Comment by CasperH2O** [comment]
The two links in the readme work fine for me. Are you trying to reach this one: https://discord.gg/cKaZ5SX8kx @cory-eheart ?

Here is an alternative: https://discord.gg/T8RgDkBfxp

**Comment by cory-eheart** [comment]
A few days after posting this the linked worked first. Must have just been a short issue. Meant to close this and forgot.
