### ISSUE TITLE
Get gyro data out of the application

### ISSUE THREAD

**Issue by Wenzy--** [Valkirie/ControllerService#262]
Hi, I'm a Unity developer. This is not an application issues. Is it possilbe to get the gyro data in Unity engine ? As I know in Unity  it can't get these data by origin API.  If there is some example/ API  that would be helpful 
-------
Find a solution finally .  https://github.com/keijiro/GyroInputTest

**Comment by CasperH2O** [comment]
What is your use case?

The most straightforward would probably be to use the virtual Dualshock 4 controller Handheld Companion creates. It has gyro and accelerometer data.

There is also JoyShockLibrary with C# Unity example: https://github.com/JibbSmart/JoyShockLibrary

I recommend you have a look and talk on the Gyro Gaming wiki, general development channel. There was someone there last month who went through a similar adventure. https://discord.gg/v47rGn7GPU

**Comment by CasperH2O** [comment]
@Wenzy-- since you mentioned you found a solution already, I'm closing this one. Feel free to discuss further or come over to Discord.
