### ISSUE TITLE
Windows 11 finds Trojan in 0.8c 

### ISSUE THREAD

**Issue by harbingeralpha** [Valkirie/ControllerService#3]
![ThreatFound](https://user-images.githubusercontent.com/5109929/144178818-60bc4c84-35e3-4317-841e-b53ba33c3bdb.png)
Downloading Controller.Service-0.8c.exe sets off Windows Defender on Windows 11. Sabsik.FL.B!ml is found. 0.4 did not set off this warning.

**Comment by Valkirie** [comment]
Thanks for reporting. I tend to believe it's a false positive. [See report from totalvirus](https://www.virustotal.com/gui/file/49298424f7998529b4036e425a06e07a850f7d3e0d24e8bcfc0bb2c09164e6bc).
Let me scan my environment.

**Comment by harbingeralpha** [comment]
I'm thinking it's a false positive also. Just wanted to note it in case anyone starts freaking out.
