### ISSUE TITLE
gyroscope didnt work on remote play ps5

### ISSUE THREAD

**Issue by myfire888** [Valkirie/ControllerService#4]
so I tried to remote play ps5. opened paladin. have enabled gyro in game setting.
I have confirmed that this is worked with dual sense that I plug into the aya neo.
so I plug the dual sense out, turn controllerservice on, and use the aya neo's controller. All buttons worked, except the gyro.

on the 1st page, the text "no gyrometer detected" and "no accelerometer detected" is unchecked and disabled.
is there some driver missing or something ?

**Comment by Valkirie** [comment]
Hey, here is what I've read online. Not sure if true, let me check.
`You can use a PS4 controller with PS5, but you can only use your PS4 pad to play PS4 games on PS5. You cannot use your DualShock 4 to play any PS5 specific games - including all those PS5 launch games. `

**Comment by myfire888** [comment]
hi,
but I dont want to use ds4 or dual sense. Like I said, I just used dual sense to confirm that gyro is supposed to be working with remote play. And there's no issue with it here. ds4 could too.

But I want to use aya neo as a controller including the gyro. I dont want to plug in anything to play. I bought aya neo expensive enough for the handheld form factor, and plug in a controller would just make it useless.

so, to be clear, I want to use aya neo itself a controller to play remote play ps4/ps5. It has been achieved, and controllerservice worked great enough for anything else, BUT just the gyroscope not working, which if I read it correctly on the front page, gyroscope should be working with controllerservice.
So please advice on how to make it working with controllerservice.
thx.

**Comment by Valkirie** [comment]
Controller Service mimic a DS4 controller to take advantage of gyroscope and accelerometer capacities of the AYA NEO. So anything that wouldn't work with a DS4 controller is not likely to work. I'll try and double check here.

**Comment by myfire888** [comment]
hi

to eliminate our doubts, I tried my ds4 with the aya neo (it was hard to find a cable usb type c to micro usb, but I found it anyway). And I can confirm u that remote play with ds4 can use gyro too.
and again I tried the controllerservice after that, and the gyro still not working

so there's some reason that the gyro won't be mimic by controller service. Everything else worked good it seems, even the touchpad that's used by touchscreen. Only the gyro wont working.

**Comment by Valkirie** [comment]
Thanks for the update. We'll figure this out 👍

**Comment by myfire888** [comment]
and my aya's gyro should be working too, because if I disable windows rotation locking, I could rotate the neo and the windows would follow to portrait and landscape as I rotate it. This proved that my aya's gyro is working too right ?

so, the situation is as follow : aya's gyro is working, the remote play with ds4 could use gyro, but it was not working with controller service (while all buttons and even touchpad worked with controller service).

**Comment by Valkirie** [comment]
Can you download this thing : https://github.com/Nielk1/VSCView/releases/download/v0.5.0.0/VSCView-0.5.0.0.zip and let me know if it recognizes your gyro movements ?

**Comment by myfire888** [comment]
hi, 
I have downloaded it and tried it. umm what is it and how to use it ?

all I see is a big box of green. I can move it with touch and drag, I could right click and choose the controller (if I used controller service it recognize it and when I choose it the aya vibrate a little). 
but that's it, after that, I dont know what's different. I tried to move the aya around and nothing. I tried to remote play ps4 and opened paladin, and still the gyro not working.

anything I should do ?

**Comment by myfire888** [comment]
oh I watched this, and the controller supposed to shown in the big green box ? 
but my controller didnt shown there at all.

**Comment by myfire888** [comment]
oic. I have to choose the theme. I chose ds4 v2, and it loads. all working, including the gyro.

**Comment by myfire888** [comment]
oh wow. I dont know why but it's now working.
u have any idea why is it working ?
maybe running the vscview helped it working ?
hmm, ohh maybe because I reinstall it just before I chose the theme on vscview (because I confused why is the controller not showing on the green box).

anyway it's working. very happy. thx very much :)
