### ISSUE TITLE
Gamepad-tester.com does not register Controller Service Xbox360 inputs anymore

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/ControllerService#41]
Observed with the latest release (need to go back a few to try where it did still work).

As title, going to [gamepad-test.com ](https://gamepad-tester.com/) with HID Mode Xbox360, no inputs are triggered and shown, sometimes the website does not even state xinput detected and just says no controller. Switching HID mode to DS4, the website works fine, switching back to Xbox360 HID, problem persists.

**Comment by 1basti1** [comment]
I don't have this issue.

**Comment by CasperH2O** [comment]
@1basti1 , thanks for confirming. I checked further, I initially tested with Firefox, with Chrome, both HID types work. So it's not controller service but FireFox. 

Closing.
