### ISSUE TITLE
Feature: Custom joystick response, curve physical joystick input to game 

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/ControllerService#42]
This feature is available within Steam's controller configuration and reWASD. Allowing the user to scale physical joystick, within given ranges to a different game input. 

Example from Steam.

![steam-controller-config](https://user-images.githubusercontent.com/14330834/154241070-6640e33d-8d80-4338-aee9-29db0a37da31.png)

Example from reWASD.

![rewasd](https://user-images.githubusercontent.com/14330834/154241290-e5a6cdb7-fcce-4457-ad25-a51667d8fdae.png)

The following "building blocks" could be used to to implement this in Controller Service

Front end
- Use the livecharts wpf library (similar as angular gauge prototype):
- Take the basic column graph from here: https://lvcharts.net/App/examples/v1/Wpf/Column
- From the same library, events for mouse/touch location feedback to scale them up and down on user touch in a certain area: https://lvcharts.net/App/examples/v1/Wpf/Events
- Alternatively for input values we could define a table (more ugly, but more precise value entry)

Back end 
We can use various interpolations:
- Linear: https://www.vedantu.com/formula/interpolation-formula
- Bicubic: https://www.paulinternet.nl/?page=bicubic

Other
- The amount of bars can be configured (within reason 4-12?)
- Allow for table of points (xy) or mouse/touch click adaption of points and or both (like reWASD)
- Allow for different types of interpolation, linear or bicubic
- Show an additional point or line to indicate the current physical joystick to game joystick input, to give users a feel for it

**Comment by Valkirie** [comment]
High priority in todo list.

**Comment by CasperH2O** [comment]
If you'd like to get started, I wrote this pseudocode in Notepad (no syntax highlighting) with a mix of python and C#. Should cover an initial basic version with 5 nodes and linear interpolation. 

```
//Assume 5 nodes, data comes from gui/profile
list_of_nodes([x, y], [x, y], [x, y], [x, y], [x, y])

// Data notes

// This is debatable, could technically allow input to start later or end earlier, sort of deadzone compensation/max reach
// Node 0 has a fixed Y value of 0
// Node 4 has a fixed Y value of 1 

// X values of all nodes have to be higher then previous and lower then next, limit in GUI and double check here

physical_joystick_pos = -1 to 1

// use absolute joystick position
joystick_pos_abs = abs(joystick_pos)

if joystick_pos_abs < node[0].x 
	#send 0 output
	output = 0
elif joystick_pos_abs > node[4].x
	# send 1 output
	output = 1
elif joystick_pos_abs > node[0].x and joystick position < node[4].x
	output = interpolation(physical_joystick_pos, list_of_nodes)
	
// Apply direction multiplier again
	output = (joystick_pos < 0.0) ? -output : output;

// Interpolation function (linear), takes list of nodes	and X
// References:
// - https://www.geeksforgeeks.org/linear-interpolation-formula/
// - https://social.msdn.microsoft.com/Forums/vstudio/en-US/46154175-541f-4728-a928-af1a852ef9f9/find-interpolation-value-between-two-arrays-in-visual-c

interpolation(physical_joystick_pos, list_of_nodes)
	// Convert xy list to separate single lists
	x, y = dual_list_to_single_list(list_of_nodes)
	
	// Figure out between which two nodes the physical joystick position is
	int i = Array.FindIndex( X, k => x <= k );
	
	// Interpolate between those two points
	double y = Y[i - 1] + ( x - X[i - 1] ) * ( Y[i] - Y[i - 1] ) / ( X[i] - X[i - 1] );
	output = y
	
	return output
	
# Convert XY list to separate X and Y lists
dual_list_to_single_list(double_value_list):
    first_pos = []
    second_pos = []

    for double_value in double_value_list:
        first_pos.append(double_value[0])
        second_pos.append(double_value[1])

    return first_pos, second_pos
```

**Comment by Valkirie** [comment]
implemented
