### ISSUE TITLE
Bug: Rumble/Motor vibration does not work for Dolphin and PCSX2

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/ControllerService#48]
As reported by skaelee on Discord. 

> When I use dolphin or pcsx2 will controller service is emulating a ps4 controller pcsx2 and dolphin would'nt find the vibration motors at all for some reason but when I turn the controller service off it finds it with my regular xinput from the controller installed inside the aya

I (Casper) double checked, indeed with DS4 selected Dolphin does not see the motors, the regular Aya controller is OK.

![afbeelding](https://user-images.githubusercontent.com/14330834/156053926-636e659c-ce7f-4aad-9a67-e417c9bb450f.png)

![afbeelding](https://user-images.githubusercontent.com/14330834/156053989-8b33a0fd-0180-4f02-90eb-6e5949391a06.png)

Further feedback:

![afbeelding](https://user-images.githubusercontent.com/14330834/156054051-922eea13-440d-4b0c-908d-17f2ce44da2b.png)

> As you can see when using controller service emulating the ps4 controller with the aya controller cloaked or un cloaked the motor isn’t recognized

**Comment by Valkirie** [comment]
Nothing we can do about it. We emulate Direct Input devices. Dolphin and a few other emulators are not properly supporting DInput. Changed Dolphin default profile so that it can access the physical controller.
