### ISSUE TITLE
Bug: New profile creation leaves empty aiming_array

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/ControllerService#54]
Symptoms, old and newly created profiles crash when additional settings page is opened due to a null pointer exception (array has no contents).

Tested with latest main branch, create new profile, check file contents:

`{
  "name": "Kena: Bridge of Spirits",
  "path": "C:\\Games\\Kena Bridge of Spirits\\Kena\\Binaries\\Win64\\Kena-Win64-Shipping.exe",
  "executable": "Kena-Win64-Shipping.exe",
  "whitelisted": false,
  "use_wrapper": false,
  "gyrometer": 1,
  "accelerometer": 1,
  "steering": 0,
  "inverthorizontal": false,
  "invertvertical": false,
  "umc_enabled": false,
  "umc_input": 0,
  "umc_output": 0,
  "aiming_sensivity": 2,
  "aiming_intensity": 2,
  "aiming_array": [],
  "steering_max_angle": 30,
  "steering_power": 1,
  "steering_deadzone": 0,
  "steering_deadzone_compensation": 0,
  "mousehook_enabled": true,
  "mousehook_exclusive": false,
  "umc_trigger": 0
}`

There is code that should run on profile creation to fill the array with linear values, but apparently it's not working?

Profile.cs:
`
        public Profile()
        {
            if (aiming_array.Count == 0)
            {
                for (int i = 0; i < array_size; i++)
                {
                    double value = (double)i / (double)(array_size - 1);
                    ProfileVector vector = new ProfileVector(value, 0.5f);
                    aiming_array.Add(vector);`

Not sure how to fix.

**Comment by Valkirie** [comment]
should be fixed with #58

**Comment by CasperH2O** [comment]
Fixed.
