### ISSUE TITLE
Disable motion control button complementary to always on

### ISSUE THREAD

**Issue by CasperH2O** [Valkirie/ControllerService#71]
Handheld Companion now features a "Always on" enable button option, however sometimes its nice to temporarily disable this to realign the device physically.

Adding a whole set of button toggle leads to a lot of clutter, perhaps a simple toggle "Motion disable button", when toggled it will enable always on greyed out (so the user can't change it) and then which ever buttons are ticked disable motion control.

**Comment by Zebrazilla** [comment]
Having used "always on" a lot, this feature is something I keep coming back to as something I wish was possible. While I'm not sure it will be as useful in practice as it feels like it will be, as I haven't tried gyro in any other context than with HC, I still believe it would be a wonderful feature.

**Comment by CasperH2O** [comment]
Did some thinking, could add a single toggle in the GUI for motion default on or off, remove the always on checkbox selection and try the following.

toggle 
off: default off, use enable button
on:  default  on, use disable button

// Understanding of current implementation:
1. Buttons is loaded with current gamepad state
2. Bitwise or operator adds left or right trigger if active, otherwise, results 0 ie nothing
3. Checks for always on custom button value
4. compare umc_trigger bitwise and with buttons, if unequal to 0, something configured to be used is being pressed

Adjusted code

```
        public virtual unsafe void UpdateReport(Gamepad Gamepad)
        {
            // get current gamepad state
            XInputGetStateSecret13((int)physicalController.UserIndex, out state_s);

            // get buttons values
            GamepadButtonFlagsExt buttons = (GamepadButtonFlagsExt)Gamepad.Buttons;
            buttons |= (Gamepad.LeftTrigger > 0 ? GamepadButtonFlagsExt.LeftTrigger : 0);
            buttons |= (Gamepad.RightTrigger > 0 ? GamepadButtonFlagsExt.RightTrigger : 0);

            // get sticks values
            LeftThumb = new Vector2(Gamepad.LeftThumbX, Gamepad.LeftThumbY);
            RightThumb = new Vector2(Gamepad.RightThumbX, Gamepad.RightThumbY);

            if (ControllerService.profile.umc_enabled)
            {
                if ((DefaultToggle == False && (ControllerService.profile.umc_trigger & buttons) != 0 ) ||
				    DefaultToggle == True && (ControllerService.profile.umc_trigger & buttons) == 0)
                {
                    switch (ControllerService.profile.umc_input)
                    {
                        case Input.PlayerSpace:
                        case Input.JoystickCamera:
                        case Input.AutoRollYawSwap:
```

**Comment by CasperH2O** [comment]
Done. ✅
